### ISSUE TITLE
Import and Export Variable from real c#

### ISSUE THREAD

**Issue by michalss** [vassilych/cscs#5]
Hi, i would like to import value from my selected source once i run the script, somewhere from my code. For example from listview or grid? Like i select something and get value from it and save it as cscs variable before any commands start process. Same for exporting variable, so example, saved some variable from cscs and i want to export it back to my code as variable. Can this be done pls ?

 Thx

**Comment by vassilych** [comment]
Hi, actually it sounds like a cool and useful feature. I am going to implement it and let you know when ready.
Thanks,
Vassili

**Comment by michalss** [comment]
Any news on this pls ? I kind of need it :)

**Comment by vassilych** [comment]
Can you give me an example of kind of C# variables that you will be using in CSCS scripts?
The problem is whether they are static or not. If static, ok, then you can mention the scope, like MyClass.MyStaticVariable. But if they are not static, how would you propose to access them?

**Comment by michalss** [comment]
any news pls?

**Comment by vassilych** [comment]
I am actually still struggling to get an example on how you can use it (I mean what kind of variables you can have in C# code that you want to access later in CSCS?)

**Comment by michalss** [comment]
well string would be enought. Simple, in void ProcessScript i would like to add variable and pass it to cscs and once script finnish to get variable back from cscs to c#. It is not hard to do it with global varialbe, but as i said threading is a problem...

**Comment by michalss** [comment]
Any update pls ?

**Comment by michalss** [comment]
Working on it pls ? Jut let me know if so or i need to make it different way.. Thx

**Comment by vassilych** [comment]
Hi, I committed it. Main file where it is defined is Statics.cs
It has the following variables, that can be updated from the CSCS code:

public static string StringVar = "";
public static double DoubleVar = 0.0;
public static bool   BoolVar   = false;
public static int    IntVar    = 0;

The CSCS functions to use are GetNative("C# variable name") and SetNative("C# variable name", value):

Here is an example in CSCS of the usage:

SetNative("StringVar", "abc");
x = GetNative("StringVar");
print("x=", x);

SetNative("DoubleVar", 123.45);
d = GetNative("DoubleVar");
print("d=", d);

Note that how is everything set up, the variables are all defined in the Statics.cs class. You can define there other variables as well, just keep "public static " for them, so that you can access those variables anywhere from your C# code, e.g.:

string x = Statics.StringVar;

Let me know if it works for you.

Cheers,
Vassili

**Comment by michalss** [comment]
Hi,

I did test it, but i still have a same problem, once u do threading with ProccessScript void, it will return you same variable a few times. Simple say, nothing change then i had it with global variable. Its bad since u cannot do threading or tasking with it.. :( That why i would do it like Start ProcessScript  as function  with return code u choose from cscs. Yes u can do it even now, but not with threading since it is global variable :(..

public static string ProcessScript(string script, string machine)


and finish it with return "something";

Like this

**Comment by michalss** [comment]
Hi,

Can this variales be instancseable pls ? I would like to get return variable per thread..

**Comment by michalss** [comment]
is there any chance to pls do it ? If so how ?

**Comment by vassilych** [comment]
Yes, these variables are static. But you can add there a unique id (e.g. just a counter, or a thread id, etc.) to make them unique per thread. E.g.:

name = "StringVar" + someId;
SetNative(name, "abc");
x = GetNative(name);
print("x=", x);
 
Wouldn't setting a unique name make the trick?

**Comment by JasonLWalker** [comment]
I am working on a module that would allow dynamic runtime import/export of variables to and from C# without the need to define and compile them in the Statics.cs file. I already have this working in some of my own projects, but will try to extract it into it's own module and commit it as a pull request soon.

**Comment by vassilych** [comment]
Hi Jason,

Looks very good! Let me merge it once I am back from my vacation on Sunday.

Thanks, Vassili
